[package]
authors = ["segler_alex"]
description = "Radio-Browser Server with REST API"
license = "agpl-3.0"
name = "radiobrowser-api-rust"
readme = "README.md"
version = "0.7.11"
edition = "2018"

[dependencies]
av-stream-info-rust = "0.10.0"
celes = "1.0.6"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "2.33.3"
colored = "2.0.0"
csv = "1.1.6"
dns-lookup = "1.0.6"
fern = { version = "0.6.0", features = ["colored"] }
handlebars = "3.5.4"
hostname = "0.3.1"
humantime = "2.1.0"
log = "0.4.14"
memcache = "0.15.0"
mysql = "20.1.0"
native-tls = "0.2.7"
percent-encoding = "2.1.0"
prometheus = { version = "0.12.0" }
rayon = "1.5.0"
redis = { version = "0.20.0" }
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
rouille = "3.0.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
serde_with = "1.7.0"
threadpool = "1.8.1"
toml = "0.5.8"
url = "2.2.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
xml_writer = "0.4.0"

[package.metadata.deb]
maintainer = "sailor <segler@programmierecke.net>"
copyright = "2018, sailor <segler@programmierecke.net>"
depends = "$auto, systemd"
extended-description = """\
Radio-Browser Server with REST API
"""
section = "admin"
priority = "optional"
assets = [
    ["target/release/radiobrowser-api-rust", "usr/bin/radiobrowser", "755"],
    ["static/*", "usr/share/radiobrowser/", "644"],
    ["init.sql", "usr/share/radiobrowser/init.sql", "644"],
    ["etc/config-example.toml", "etc/radiobrowser/config-example.toml", "644"],
    ["etc/config-example.toml", "etc/radiobrowser/config.toml", "644"],
    ["etc/logrotate", "etc/logrotate.d/radiobrowser", "644"],
]
conf-files = [
    "etc/radiobrowser/config.toml",
]
maintainer-scripts = "debian/"
systemd-units = { unit-name = "radiobrowser", enable = false }