version: "3.2"
services:
  api:
    build: ./
    image: segleralex/radiobrowser-api-rust:0.7.4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${SOURCE}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=redirecttls"
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.middlewares.redirecttls.redirectscheme.scheme=https"
      - "traefik.http.routers.apitls.rule=Host(`${SOURCE}`)"
      - "traefik.http.routers.apitls.entrypoints=websecure"
      - "traefik.http.routers.apitls.middlewares=compress"
      - "traefik.http.routers.apitls.tls.certresolver=letsencrypt"
    deploy:
      replicas: 1
    networks:
      - mynet
    environment:
       - SOURCE
       - ENABLE_CHECK
       - DATABASE_URL=mysql://radiouser:password@dbserver/radio
       - HOST=0.0.0.0
  dbserver:
    image: mariadb:10.4
    deploy:
      replicas: 1
    environment:
       - MYSQL_ROOT_PASSWORD=12345678
       - MYSQL_USER=radiouser
       - MYSQL_PASSWORD=password
       - MYSQL_DATABASE=radio
    networks:
      - mynet
    volumes:
      - ./dbdata:/var/lib/mysql
    command: ["mysqld","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command:
      #- "--api=true"
      - "--log.level=INFO"
      - "--providers.docker=true"
      #- "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesResolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      #- "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    networks:
      - mynet
networks:
  mynet:
    driver: "overlay"
    driver_opts:
      encrypted: ""
